{% set name = "pygad" %}
{% set version = "2.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: d39e1d70624c40e2c6508fb2ac7515a452d9f89daf6606bfd6761dcb46b31ef2

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4f6dcae2a50173606eb70f301d1067fedad30f969b8e459888f6fc9cfaae4e8f
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - traversaro
