{% set name = "pygad" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: 0e4f028b2ed8c06839fde437453f6f06da0d5d2f54e77b2a83ff43c1bf978d44

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: ade912417a0994be42490be4015b9612c30008c1b46f963c2b66fc80e6d193e7
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - cloudpickle

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - traversaro
